
CREATE TABLE `pawn`.`tbloverpayment` (
  `OVERPAYID` int(11) NOT NULL,
  `PRODUCTID` int(11) DEFAULT NULL,
  `TICKETID` int(11) DEFAULT NULL,
  `DUETYPEID` int(11) DEFAULT NULL,
  `OVPAMOUNT` decimal(15,2) DEFAULT NULL,
  `RCPID` int(11) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `LASTUPTIME` mediumtext,
  `LASTUPUSERID` int(11) DEFAULT NULL,
  `VERSIONID` int(11) DEFAULT NULL,
  `COMID` int(11) DEFAULT NULL,
  `BRANCHID` int(11) DEFAULT NULL,
  `RECSTATUS` int(11) DEFAULT '0',
  `ORIGINALID` int(11) DEFAULT '0',
  PRIMARY KEY (`OVERPAYID`)
) ;tbloverpayment

